---
- name: Gather facts - need ansible_distribution_release
  setup:
    gather_subset: all
  changed_when: false

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu/ {{ ansible_distribution_release }} stable
    update_cache: no
    state: present

- name: Update Cache
  apt:
    update_cache: yes
 
- name: Install prerequisites
  apt:
    name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release', 'git', 'python3-pip' , 'net-tools']
    state: present

# Uncomment this line to remove everything that spins around docker, swarm and swarmpit. If versions changed.
#- include: purge.yml

- name: Install docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    state: present
    update_cache: no

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.23.2/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Install docker-py
  pip:
    name: ['docker==6.1.3','docker-compose']
    state: present

# - name: Add the user 'imran' to group 'docker' to run docker without sudo
#   ansible.builtin.user:
#     name: imran
#     append: yes
#     group: imran
#     groups: docker